name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /property:${{GITHUB_RUN_NUMBER}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push to nuget.org
      run: dotnet nuget push "**/Release/*${{GITHUB_RUN_NUMBER}}*.nupkg" --source "nuget.org" --api-key ${{secrets.NUGET_API_KEY}}
